#!/bin/sh

#SBATCH --job-name=ds000237-mriqc
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000237-mriqc/.reproman/jobs/local/20220824-211140-248f/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000237-mriqc/.reproman/jobs/local/20220824-211140-248f/stderr

#SBATCH --nodes=3
#SBATCH --ntasks=13
#SBATCH --time=8:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000237-mriqc/.reproman/jobs/local/20220824-211140-248f

module load launcher
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 12); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

"$LAUNCHER_DIR"/paramrun